[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
alebrije_coin = "93CCq4xaFrrEmoD8DtwD8rjuizZddBrnZYv3p7oQSSTz"

[programs.mainnet]
alebrije_coin = "HMm5qCTN1uag7gJACT8zW9wckbJe2iC78RbPqG4FaWxh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/rastavo/alebrije-wallet/mint-authority-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "93CCq4xaFrrEmoD8DtwD8rjuizZddBrnZYv3p7oQSSTz"
program = "target/deploy/alebrije_coin.so"
