[build]
  command = "npm install && npm run build"
  publish = "build"
  base = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = "build"
  autoLaunch = true 