blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/alebrijetoken
    about: Join our Discord community for support and discussions
  - name: Documentation
    url: https://alebrije-inu.netlify.app/docs
    about: Check our documentation for guides and FAQs
  - name: Security Policy
    url: https://alebrije-inu.netlify.app/security
    about: Read our security policy and responsible disclosure guidelines 